FROM node:18-alpine
WORKDIR /app

# Install dependencies strictly for production
COPY package*.json ./
RUN npm ci --only=production

COPY . .

# Generate Prisma client
RUN npx prisma generate

EXPOSE 5000
CMD ["npm", "start"]
