FROM node:22-alpine
WORKDIR /app

RUN apk add --no-cache openssl

# Install dependencies strictly for production
COPY package*.json ./
RUN npm ci

COPY . .

# Generate Prisma client
RUN npx prisma generate

EXPOSE 5000
CMD ["npm", "start"]
